import Foundation

let suite = Suite()

print("TypeAhead — full suite")
runRankerTests(suite)
runAcceptanceControllerTests(suite)
runContextReaderTests(suite)
runMemoryTests(suite)
runBackoffTests(suite)
runCalibrationTests(suite)
runSnippetTests(suite)
runBoundaryTests(suite)
runMigrationTests(suite)
runMidWordTests(suite)
runHygieneTests(suite)
runEditDistanceTests(suite)
runModelTests(suite)
runLexiconTests(suite)
runGrammarTests(suite)
runLemmaTests(suite)
runStaleSuggestionTests(suite)
runInlineGhostTests(suite)
runInlineSafetyTests(suite)
runThreadingTests(suite)
runSubstitutionTests(suite)
runTypedGhostTests(suite)
runPortabilityTests(suite)
runSavingsTests(suite)
runIntegrationTests(suite)
runDesignRuleTests(suite)

suite.finish()
